[main]
font=monospace:size=12
prompt=❯ 
layer=overlay
lines=12
width=40
horizontal-pad=16
vertical-pad=12
inner-pad=8

[colors]
# Kanagawa Wave Palette
background=1f1f28ff
text=c8c097ff
match=c4746eff
selection=2d3149ff
selection-text=dcd7ba99
border=54546dff

[border]
width=2
radius=8

include=/home/navin/.config/fuzzel/themes/noctalia
